### PR TITLE
FIX Macosx mysql2 crash

### PR DESCRIPTION
**Pull request by losingle**

### CODE REVIEW

**Comment by willpower232** [comment]
Can you explain what problem this fixes?

Also I don't think you've created any migrations so these database changes would probably cause problems for existing users.

**Comment by losingle** [comment]
It does not change the migration file name and will not affect existing user upgrades.

MySQL 8.0.13
Ruby: 2.6.2
Rails: 5.2.2.1
mysql2: 0.4.10
Macos: 10.15 Beta (19A512f)

mysql2 problem: https://github.com/brianmario/mysql2/issues/1036
Fix issues: https://github.com/brianmario/mysql2/issues/990#issuecomment-403095886


[crash.log](https://github.com/atech/postal/files/3456302/crash.log)

**Comment by willpower232** [comment]
The update might be useful for #757 because of MySQL 8 however Postal should definitely be run on a true server, not a MacOS Desktop.

**Comment by losingle** [comment]
Yes, but should you also consider using macosx to debug your friends?

**Comment by adamcooke** [comment]
This isn't a very clean merge just to update the mysql2 gem. On that basis, I'm going to close this. I'll handle an upgrade of this when I do the full Rails upgrade shortly.

**Pull request closed without merging**
