### PR TITLE
Added the ability to disable signup

### PR DESCRIPTION
**Pull request by deanpcmad**
I noticed that there was a signup option on the login page. Ideally on a private setup this should be disabled to prevent random people from signing up so I've added the `disable_signup` option to disable this 😄

### CODE REVIEW

**Comment by stayallive** [comment]
You should also add the logic to the create method since if I know the route and what parameters to sent I can create an account anyway without using the gui :)

**Comment by adamcooke** [comment]
It's not quite this simple. Users need to be able to signup when they are invited to an organization. There's no harm in other users existing but simply disabling it will stop any user from being created. I agree this should exist but some logic will need to be put in place to avoid stopping invited users from creating accounts. A change to the way invites work is likely needed here.

**Comment by deanpcmad** [comment]
Ah OK, is the URL different when a user is invited? Maybe it can be made to add a unique param to the end of the signup page to allow that user to signup even if the main signup page is disabled?

**Comment by stayallive** [comment]
Some kind of hash for the specific signup would definitly be an option @deanpcmad, that is how most systems handle it now-a-days. A random hash could be appended to the user invite (in the `user_invite` database table, and appending that to the url allowing the signup logic to be enabled when the login/signup page is accessed with the random hash in the url.

**Comment by stayallive** [comment]
I noticed a singup already has an uuid and already sents it in the url `/join/:uuid` so I created a simple before filter (stayallive/postal@13ba72d5b26857b64def15210bd990248d825e1e) to validate the invite token before allowing user signup. Would this be a acceptable solution @adamcooke?

If so @deanpcmad can merge deanpcmad/postal#1 and then this PR can also be merged, pulling in both our changes 💯

**Comment by deanpcmad** [comment]
Sounds fine to me. What do you think @adamcooke

**Comment by stayallive** [comment]
@deanpcmad if you merge in deanpcmad/postal#1 this PR can be reviewd (maybe fix the conflicts in the `postal.defaults.yml` too while you are at it).

**Comment by stayallive** [comment]
@adamcooke could you take another peek at this or let us know if you are working on it elsewhere. Would be a very welcome (and secure) addition to Postal.

**Comment by adamcooke** [comment]
I've actually gone about this slightly different. Rather than having an option for this, all signups can only happen once you have been invited to an organization. When an invite goes out, it will take you to a page to create a new account or login to your existing one.

New users who signup in this way also don't need to verify their email address because they will already have done so by clicking the original signup link.

**Comment by stayallive** [comment]
Perfect! Thanks @adamcooke!

**Comment by deanpcmad** [comment]
Sounds good 👌

**Pull request closed without merging**
