### PR TITLE
Fix for Issue #228

### PR DESCRIPTION
**Pull request by alexander-rieder**
PR for changes made by @alexroosenstein #228

### CODE REVIEW

**Comment by willpower232** [comment]
This is probably heavily related/conflicting with #376 probably should have made the association sooner...

**Comment by alexander-rieder** [comment]
So what are the next steps?

**Comment by willpower232** [comment]
This code looks like it always creates html and plain body parts so could be a reversion of #267 (I'm not sure how the ruby mail class would cope with receiving `nil` as a part) and other than that it accomplishes the same as #376 so I'd say this should be closed in favour of that, sorry

I was never able to replicate #288 but did get some feedback from our recipients that they didn't get the attachments through so I was testing with downloading the EML and that lead to #376.

**Comment by alexander-rieder** [comment]
so #376 fixes also #228 ? If yes, then go for #376 ;)

**Pull request closed without merging**
