### PR TITLE
Bump Rails to 5.2.1

### PR DESCRIPTION
**Pull request by greysteil**
This *should* be backwards compatible - it has a pretty good [compatibility score](https://dependabot.com/compatibility-score.html?dependency-name=rails&package-manager=bundler&previous-version=5.1.6&new-version=5.2.0) on Dependabot.

### CODE REVIEW

**Comment by greysteil** [comment]
> Sorry to ask, do you run Postal to know its backwards compatible?

I haven't run locally because I didn't have mysql installed when creating this. I'll add it now and take a look, but I'm pretty confident.

> Also did you mean to also change config/initializers/new_framework_defaults.rb?

Yep - that setting was removed in 5.2. Postal was already setting it to the value that is now the default.

**Comment by greysteil** [comment]
Have spent the last two hours trying to get a mysql install and get the test running, but something's wrong with my setup and I'm getting nowhere. 😢

If you can easily test this then that would be amazing.

**Comment by catphish** [comment]
I will get this tested myself and get the update out as soon as I can.

**Comment by catphish** [comment]
I've done this upgrade. Sorry I didn't use this pull request :slightly_smiling_face:

**Comment by greysteil** [comment]
No worries!

Would it be a horrible pain to get Travis/CircleCI set up for this repo? I had a horrible time trying to get the tests to run and it would have made my life way easier. Unfortunately my inability to run the tests locally makes me a bad candidate to submit a PR!

**Pull request closed without merging**
