### PR TITLE
move 'Add domain' button on top of Domains page.

### PR DESCRIPTION
**Pull request by valentin2105**
Hi,

It would be awesome if the 'Add domain' button can be on top of the domains list page. 

When managing tons of domain on Postal, is annoying to go on bottom each time we want to add a domain. 

Thanks !

### CODE REVIEW

**Comment by willpower232** [comment]
Looks good but if you're managing so many domains that you have to scroll to add more, have you considered setting up other organisations or servers within Postal to separate out clients/projects?

**Comment by valentin2105** [comment]
Yes Will, we manage different projects but we got any with all our virtual
servers for send their own system mail via postal to admins inbox.
One domain per machine so.
Thanks for the tips otherwize ;)

**Comment by catphish** [comment]
Apologies for the terrible workflow. I merged this to test, and I'm afraid I didn't like it from a design perspective. The view looks wrong (and inconsistent with other pages) then only a couple of domains are present. Sorry!

**Comment by valentin2105** [comment]
@catphish  I understand, no problem. I keep this on my local instance ;)

**Pull request merged**
