### PR TITLE
Add ability to always redeliver messages regardless of status or development mode

### PR DESCRIPTION
**Pull request by LaurensN**
See issue #223

### CODE REVIEW

**Comment by LaurensN** [comment]
@adamcooke Can we merge some open PR's ?

**Comment by mattmartincouk** [comment]
This does not seem to work on messages that have actually been sent.

You get an error with "This message is no longer queued for sending.".

**Comment by LaurensN** [comment]
@mattmartincouk Are you testing this in an environment other than production ? It seems  `MessagesController#retry` also needs a minor adjustment to support this functionality https://github.com/atech/postal/blob/2f0155747c5c058afb83856ce5c3c8d5f8cad341/app/controllers/messages_controller.rb#L110

**Comment by mattmartincouk** [comment]
Might be worth submitting that with this PR then.

I am testing on a copy of our live install using live data as it was yesterday.

**Comment by LaurensN** [comment]
@mattmartincouk Alright, adjusted the PR accordingly.

**Comment by mattmartincouk** [comment]
That works - this PR works well as far as I can see.

**Comment by mattmartincouk** [comment]
The only other suggestion I would make is that the option to resend should not be given if the message is no longer stored. Otherwise, it then generates a fail but that makes it look like a SMTP issue than a local one.

**Comment by catphish** [comment]
I have written my own version of this fix: 53475abf553a65d7aaac91cf99e74b104e7bd9cb
It takes on @mattmartincouk's concern about the raw message no longer being stored.

**Pull request closed without merging**
